import type { CefrLevel, LearningLanguage } from '../../lib/learning';
import type { InterfaceLanguage } from '../../i18n';
import type { PathCopy } from './types';

export function buildPracticePathCopy(language: LearningLanguage, level: CefrLevel, interfaceLanguage: InterfaceLanguage, displayLanguage = language): PathCopy {
  if (interfaceLanguage === 'de') {
    return {
      pageEyebrow: 'Übungsweg',
      title: 'Mein Lernweg',
      intro: 'Folge dem Lernweg für deine ausgewählte Sprache und dein aktuelles GER-Niveau.',
      lessonsTitle: `${displayLanguage} ${level} Lektionen`,
      lessonsSummary: '12 Lektionen mit Hören, Diktat, Lesen, Sprechen, Schreiben, Wiederholung und Fortschrittsprüfung.',
      syncingProgress: 'Fortschritt wird synchronisiert',
      syncingPath: 'Lernweg wird aktualisiert',
      syncError: 'Der Übungsfortschritt konnte nicht synchronisiert werden:',
      curriculum: 'Dein Plan',
      pathCount: '12 Lektionen',
      lessonCount: 'Lektionen',
      lessonLabel: 'Lektion',
      selectedLesson: 'Ausgewählte Lektion',
      goal: 'Ziel',
      canDo: 'Kann ich',
      grammar: 'Grammatik',
      lessonWords: 'Lektionswörter',
      overviewEyebrow: 'Lernweg-Überblick',
      overviewTitle: 'Ein klarer Weg von heute bis zur freien Anwendung',
      overviewIntro: 'Deine Lektionen folgen einer ruhigen Reihenfolge: Hören, Diktat, Lesen, Schreiben, Wiederholung und Fortschrittsprüfung.',
      viewCurriculum: 'Vollständigen Lehrplan ansehen',
      lessonFlow: 'Lektionsablauf',
      currentLevelMap: 'Aktuelle Niveaukarte',
      levelMapFallback: 'Deine Lektionen sind unten bereit. Eine tiefere Niveaukarte für diese Sprache erscheint, wenn der Lehrplan erweitert wird.',
      stepLabel: 'Schritt',
      fromToLabel: 'Von',
      toLabel: 'bis',
      withLabel: 'mit',
      practiceStepsLabel: 'Übungsschritten pro Lektion',
      skillFlowLabels: ['Hören', 'Diktat', 'Lesen', 'Sprechen', 'Schreiben', 'Wiederholung', 'Fortschrittsprüfung'],
      aiEyebrow: 'KI-Übung',
      aiTitle: `Übungstext für ${displayLanguage} ${level} erstellen`,
      aiDescription: 'Erstelle niveaugerechtes Material für Diktat, Hören, Lesen oder Schreiben und nutze es in deinem aktuellen Lernweg.',
      checkingAccess: 'KI-Zugang wird geprüft',
      generate: 'Für mein Niveau erstellen',
      premiumTitle: 'Premium-KI-Übungen sind gesperrt',
      premiumDescription: 'Kostenlose Nutzer können dem Übungsweg folgen. Pro schaltet KI-generierte Texte für jedes Niveau und jede Fertigkeit frei.',
      upgrade: 'Upgrade',
    };
  }

  return {
    pageEyebrow: 'Practice Path',
    title: 'My Learning Path',
    intro: 'Follow the learning path created from your selected language and current CEFR level.',
    lessonsTitle: `${displayLanguage} ${level} Lessons`,
    lessonsSummary: '12 lessons with listening, dictation, reading, speaking, writing, review, and progress checks.',
    syncingProgress: 'Syncing progress',
    syncingPath: 'Updating path',
    syncError: 'Practice progress could not sync:',
    curriculum: 'Your plan',
    pathCount: '12 lesson path',
    lessonCount: 'lessons',
    lessonLabel: 'Lesson',
    selectedLesson: 'Selected lesson',
    goal: 'Goal',
    canDo: 'Can do',
    grammar: 'Grammar',
    lessonWords: 'Lesson words',
    overviewEyebrow: 'Path overview',
    overviewTitle: 'A clear route from today to fluency',
    overviewIntro: 'Your lessons move through listening, dictation, reading, writing, review, and progress checks in a steady order.',
    viewCurriculum: 'View full curriculum',
    lessonFlow: 'Lesson flow',
    currentLevelMap: 'Current level map',
    levelMapFallback: 'Your lesson list is ready below. A deeper level map for this language will appear as the curriculum expands.',
    stepLabel: 'Step',
    fromToLabel: 'From',
    toLabel: 'to',
    withLabel: 'with',
    practiceStepsLabel: 'practice steps per lesson',
    skillFlowLabels: ['Listening', 'Dictation', 'Reading', 'Speaking', 'Writing', 'Review', 'Progress Check'],
    aiEyebrow: 'AI practice',
    aiTitle: `Generate practice text for ${displayLanguage} ${level}`,
    aiDescription: 'Create level-aligned dictation, listening, reading, or writing material and add it to your current path.',
    checkingAccess: 'Checking AI access',
    generate: 'Generate for my level',
    premiumTitle: 'Premium AI practice is locked',
    premiumDescription: 'Free users can follow the practice path. Pro unlocks AI-generated texts for each level and skill.',
    upgrade: 'Upgrade',
  };
}

