export type ShadowingWord = { text: string; start: number; end: number };

export type ShadowingSegment = {
  id: string;
  text: string;
  start: number;
  end: number;
  words?: ShadowingWord[];
  status: 'locked' | 'current' | 'completed' | 'retry';
  attempts: ShadowingAttempt[];
  lastRecordingUrl?: string | null;
  lastRecordingMimeType?: string | null;
};

export type RecordingContext = { segmentId: string; segmentIndex: number; targetText: string };

export type ShadowingAttempt = {
  score: number;
  transcript: string;
  missingWords: string[];
  incorrectWords: string[];
  passed: boolean;
  createdAt: string;
  engine?: 'browser' | 'gemini-audio';
  model?: string;
  audioPath?: string | null;
  audioMimeType?: string | null;
};

export type YouTubeTranscriptCue = { text: string; start: number; duration: number };

export type YouTubeTranscriptResponse = {
  videoId: string;
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
  text: string;
  cues: YouTubeTranscriptCue[];
  source?: 'cache' | 'youtube';
};

export type ShadowingSession = {
  id: string;
  title: string;
  videoUrl: string;
  videoId: string;
  language: string;
  level: string;
  completed: number;
  total: number;
  averageScore: number;
  bestScore: number;
  difficultSentences: string[];
  missedWords: string[];
  transcript?: string;
  segments?: ShadowingSegment[];
  currentIndex?: number;
  transcriptSource?: string | null;
  remoteId?: string;
  updatedAt: string;
  status: 'in_progress' | 'completed';
};
